# Generated by Django 5.1.3 on 2024-11-27 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('genre', models.CharField(max_length=100)),
                ('year', models.IntegerField()),
                ('rating', models.FloatField(default=0.0)),
                ('video', models.FileField(blank=True, null=True, upload_to='movies/videos/')),
            ],
        ),
    ]
